### ISSUE TITLE
교육 수강 확인서 문의

### ISSUE THREAD

**Issue by kimhw7** [preonboarding-internship/wanted-preonboarding-qna-9th#1]
예비군 연기하려 하는데 교육 수강중인걸 증명할 수 있는 서류가 필요하다고 해서
제가 교육 수강중인걸 확인할 수 있는 서류 발급받을 수 있는게 있을까요?

**Comment by walking-sunset** [comment]
안녕하세요, 운영에 관련된 질문은 디스코드의 "질문-운영" 채널을 이용해주시기 바랍니다 :)
