### ISSUE TITLE
회원가입 api response body teken 여부 관련 질문 

### ISSUE THREAD

**Issue by whl5105** [preonboarding-internship/wanted-preonboarding-qna-9th#2]
안녕하세요 9조 팀원 최수인입니다

팀 과제를 진행하는 과정에서 현제 회원가입 api 응답이 선발 과제 응답 예시랑 다르게 들어와서 질문드립니다.

기존 선발 과제에는 회원가입 body 없음에서 토큰이 들어오고 있습니다 해당 토큰 들어오는 내용을 참고해서 코드를 구현하면 되는 걸까요?

**기존 응답** 
<img width="875" alt="image" src="https://user-images.githubusercontent.com/73993670/220830586-d596bb71-349d-44c7-8685-20170156468b.png">

**현재 응답**
<img width="511" alt="image" src="https://user-images.githubusercontent.com/73993670/220830696-e269ac03-d071-4a0c-ab39-5f07e0535e4b.png">
<img width="493" alt="image" src="https://user-images.githubusercontent.com/73993670/220830721-ea1bd160-efaa-4d19-a385-8842b55c0fe9.png">

**Comment by walking-sunset** [comment]
안녕하세요 수인님, API 서버단에서 구버전으로 API가 롤백이 되어있었네요, 사전과제 명세서에 적힌 API 설명대로 body 응닶 없는것으로 생각하고 작업 진행하시면 됩니다, API도 명세서와 일치하도록 수정될 예정입니다!

**Comment by walking-sunset** [comment]
API 수정 완료되었습니다 :)
