### ISSUE TITLE
pre-commit hook에서 formatting 설정 관련 이슈

### ISSUE THREAD

**Issue by jaypedia** [preonboarding-internship/wanted-preonboarding-qna-9th#3]
안녕하세요! 첫번째 주에서 알려주셨던 husky 및 pre-commit 관련하여 질문사항이 있습니다. 
수업에서 알려주신 대로 package.json에   `"format": "prettier --cache --write ."` 을 추가 후, `npx husky add .husky/pre-commit "npm run format"`을 실행하여 커밋 전에 무조건 formatting을 진행하도록 세팅하였습니다. 

이렇게 하는 목적은 "커밋을 하기 전에 formatting을 한 후, 그 포맷팅이 된 코드를 커밋하도록 하기"로 알고 있었습니다.
그러나 실제로 실행해 보니, **커밋이 된 후에 formatting이 적용**됩니다. 즉, 포맷팅이 되지 않은 상태로 커밋이 되고 있습니다. 
포맷팅은 커밋이 된 후 진행되므로, 변경 사항이 또다시 발생합니다. 이것은 강사님의 의도와는 다른 결과인 것 같다는 생각이 들었습니다. 사실상 포맷팅이 적용되지 않은 상태로 커밋이 되는 것을 방지하려고 이 hook을 쓰는 것인데, 적용되지 않고 있으니까요. 

그래서 포맷팅이 적용된 후에 커밋이 되게 하기 위해 어떻게 하면 될지 찾아봤는데, 다음과 같은 명령어를 찾을 수 있었습니다. 
```
npm run format && git add -A .
```
이렇게 하면 포맷팅을 한 후, -A 라는 옵션을 통해 모든 변경 내용이 있는 파일이 스테이징 영역에 올라간 후, 커밋이 됩니다.
하지만 이 명령어에도 문제가 있는데, 원하는 파일만 선택해서 스테이징 영역에 추가할 수가 없다는 것입니다. 

강의에서 말씀하신 목적대로 "포맷팅이 적용된 후 커밋이 되도록" 하려면, 강의 교안에 나온 명령어를 수정해야 되지 않을까 싶어서 이슈를 남깁니다.

**Comment by greyHairChooseLife** [comment]
안녕하세요, 같이 인턴쉽 프로그램에 참여 중인 사람입니다. 이슈가 아직 닫혀있지 않아서 혹시 도움이 될까 하는 마음에 코멘트 남깁니다.

두 번째 문단에 "_실제로 실행해 보니, 커밋이 된 후에 formatting이 적용됩니다._"라고 말씀하신 것에는 오류가 있습니다. 정확히는 formatting이 적용 되면서 modified 됐고, 이 같은 변경 사항이 git stage에 올라가지 않은 채로 커밋이 완료 된 것 뿐입니다.

이를 참고 삼아 `.husky/pre-commit` 파일을 수정해서 원하는 파일만 다시 `git add`하는 등 다양한 방식으로 스크립트를 활용하실 수 있습니다. 

예를 들어 `git diff --cached --name-only` 같은 명령을 통해 스테이지에 올라 와 있는 파일명만 출력 할 수 있습니다. 이를 이용하면 기존에 staged 된 것들만 다시 add 할 수 있을 것입니다.

끝까지 파이팅해요, 우리!!

**Comment by walking-sunset** [comment]
안녕하세요, 일단 강의 내용에 대한 피드백 감사드립니다 :)

말씀하신대로 스테이징만되고, 커밋이 안되는 현상은 강의 교안을 처음 접할 때 쉽게 하실 수 있게 복잡한 부분을 일부 제외하고 흐름을 단순하게 가져가기 위해서 큰그림 위주로 전달하기 위해서 일부 요소들을 제외하는 과정에서 발생한 이슈입니다.

일단, 말씀하신대로 스테이징만 되고 커밋이 안되는 문제를 해결하기 위해서는 답변 주신 동료분처럼 여러 git command를 조합해서 다시 커밋이 돌아가게 할 수 있습니다. 그리고, 저런 커맨드를 조합하는게 다소 복잡하고, 또 여러가지 엣지케이스들까지 고려하다보면 복잡성이 올라가기 때문에 일반적으로 많이 쓰는 솔루션은 [lint-staged](https://github.com/okonet/lint-staged)이란 패키지를 이용해서 staging된 파일에 대해서만 커맨드를 적용시키는 방법을 많이 사용합니다.

일반적으로 husky + lint-staged 조합의 사용예시를 보면 commit전에 formatting과 linting을 모두 수행한 뒤에 커밋을 진행하는데, 저는 개인적으로 커밋은 언제든지 자주 할 수 있게 만들어두는것이 좋다고 생각해서 commit 전 단계에서는 formatting만 수행한 뒤에 push전에 lint 검사를 하도록 세팅하는 편입니다. 예전에 적용해본 결과 lint검사를 커밋 전에 추가해두니까 필요한 순간에 커밋이 안되서 기능을 끄고, 커밋한 뒤에 다시 기능을 켜서 불편하게 사용하는 경우도 있더라고요 이건 관점의 차이라서 개인별로, 팀별로 자기가 좀 더 좋다고 생각하는 방향으로 진행하시면 될 것 같습니다.

별개로, 강의 교안은 질문자님이 말씀주신 것처럼 혼동할 수 있는 여지가 있기에 거기에 대한 부연설명을 추가하는 식으로 수정할 예정입니다.

피드백 감사드리며, 제 개인 사정으로 인해 이슈에 대한 응답이 늦어져서 오래 기다리셨을 것 같네요 😢, 답변이 도움이 되셨길 바랍니다.

그리고 9차 참가자분들 모두가 이슈가 올라오면 고민하고 자유롭게 코멘트달며 해결책을 찾아가는 문화가 자리잡혔으면 하는 바램이 있는데, 그 시작점을 잘 끊어주신 답변 코멘트 다신 분께도 감사드립니다. 앞으로도 이슈 올라오면 동료학습차원에서 같이 고민하고 자유롭게 의견을 다는 문화가 활성화됬으면 좋겠으며, 저도 멘토이자 한명의 동료 개발자로서 함께 제 의견 코멘트로 달아서 도움이 될 수 있도록 노력하겠습니다 :)
