### ISSUE TITLE
redux toolkit slice 나누는 기준

### ISSUE THREAD

**Issue by dlwnstjrzz** [preonboarding-internship/wanted-preonboarding-qna-9th#4]
안녕하세요 redux toolkit을 사용하다가 고민이 생겨서 질문하게 되었습니다.

## 질문 사항
redux toolkit의 slice를 나누는 기준이 팀원마다 달랐습니다. 모든 상태를 하나의 slice에 포함시키는 팀원도 있었고 2개의 slice에 나눠서 관리하는 팀원도 있었는데 어떤 기준으로 나눠야할지 결론이 나지 않았습니다.

저희가 우선적으로 내린 결론은 product 관련된 상태를 관리하는 productSlice와 reservation 관련 상태를 관리하는 reservationSlice로 분리하여 관리하자는 것이었습니다.
이렇게 2개의 slice로 분리한 이유는 product 관련된 상태와 reservation 관련된 상태가 공유되지 않고 독립적으로 사용된다고 생각했기 때문입니다.

slice를 어떤 기준으로 나누는게 좋을까요??

**Comment by walking-sunset** [comment]
안녕하세요, 정확한 코드를 확인할 수 없어서, 제공해주신 정보만으로 판단 후 답변드리겠습니다.

일단 현재 상황이 Redux를 사용하고 있고, 관리해야 하는 상태는 product와 reservation 두가지 범주가 있는 상황, 그리고 두 상태는 서로 공유되지 않고 독립적인 상황이라고 판단하겠습니다.

결론부터 말씀드리자면 두개의 slice로 분리한 것이 옳은 선택입니다. 세션 간 말씀드렸던 SRP관점에서 보자면 product와 reservation은 각기 독립된 관심사이기에 분리해두면 product에 대한 수정이 필요할 때 reservation slice는 건드리지 않고, product slice만 수정해서 목적을 달성할 수 있게 됩니다. 만약 한개의 reducer로 합쳤다면, product 또는 reservation 둘중 하나에 대한 변화가 필요할 때 계속해서 합쳐진 reducer를 건드려야 할 것이고, reducer에 담긴 로직들도 점점 복잡해질 수 있기에 유지보수가 힘들어질 것 같네요!

**Comment by walking-sunset** [comment]
그리고 결국 Redux의 slice를 나누는 기준으로 물어봤지만 Redux도 전역 상태 관리 도구이기에 근본적으로는 상태를 어떤 기준으로 나누고 합칠지에 대해 고민해보는게 좋으실 것 같네요, 해당 부분은 새로나온 리액트의 베타 문서에 잘 설명되어 있는 부분이 있어 참고하시며 공부해보시면 좋을 것 같네요

https://beta.reactjs.org/learn/choosing-the-state-structure

**Comment by greyHairChooseLife** [comment]
@dlwnstjrzz

멘토님이 이미 답변 주신 내용이지만.. 하나의 slice로 관리하자신 분은 어떤 근거로 그렇게 말씀하시는지도 궁금하네요.
